default: &default

development:
  <<: *default
  google_client_key_one: '771112417224-i35i1bc14bb782r3sn18abnrikaeqs4f.apps.googleusercontent.com'
  google_client_key_two: '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'
  linkedin_client_key_one: '77joqp4e4pl0qx'
  linkedin_client_key_two: 'Zz7l0osSDUXBS7Mp'

test:
  <<: *default

staging:
 <<: *default

production:
  <<: *default
